version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: shortly
      POSTGRES_PASSWORD: shortly
      POSTGRES_DB: shortly
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shortly"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # auth-service:
  #   build:
  #     context: ./apps/auth
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3001:3001"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #   environment:
  #     - NODE_ENV=development
  #     - DATABASE_URL=postgresql://shortly:shortly@postgres:5432/shortly
  #     - REDIS_URL=redis://redis:6379
  #     - JWT_SECRET=your-jwt-secret-key
  #     - JWT_EXPIRES_IN=1h
  #   volumes:
  #     - ./apps/auth:/usr/src/app
  #     - /usr/src/app/node_modules

  # url-shortener:
  #   build:
  #     context: ./apps/url-shortener
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #     auth-service:
  #       condition: service_started
  #   environment:
  #     - NODE_ENV=development
  #     - DATABASE_URL=postgresql://shortly:shortly@postgres:5432/shortly
  #     - REDIS_URL=redis://redis:6379
  #     - AUTH_SERVICE_URL=http://auth-service:3001
  #   volumes:
  #     - ./apps/url-shortener:/usr/src/app
  #     - /usr/src/app/node_modules

volumes:
  postgres_data:
  redis_data:
